spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties.hibernate.format_sql: true

  datasource:
    url: jdbc:h2:mem:meetingroom
    username: sa
    password: sa
    initialize: false

  resources:
    add-mappings: false

# Enabling H2 Console
spring.h2.console.enabled: true

# exception handling
spring.mvc.throw-exception-if-no-handler-found: true
