spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:meetingroom
    username: sa
    password: sa
    initialize: false

# Enabling H2 Console
spring.h2.console.enabled: true