server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties.hibernate.format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/meetings
    username: admin
    password: admin
#    initialization-mode: always
#    schema: classpath:/database/schema.sql # Schema (DDL) script resource references.
#    data: classpath:/database/data.sql # Data (DML) script resource references.
